services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000